

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Component Parts &mdash; cqparts 0.2.1 documentation</title>
  

  
  
  
  

  

  
  
    

  

  
  
    <link rel="stylesheet" href="../../_static/css/theme.css" type="text/css" />
  

  
    <link rel="stylesheet" href="../../_static/css/custom.css" type="text/css" />
  

  
        <link rel="index" title="Index"
              href="../../genindex.html"/>
        <link rel="search" title="Search" href="../../search.html"/>
    <link rel="top" title="cqparts 0.2.1 documentation" href="../../index.html"/>
        <link rel="up" title="Example: Easy Install" href="index.html"/>
        <link rel="next" title="Exactly Sized Fastener" href="exact-fastener.html"/>
        <link rel="prev" title="Example: Easy Install" href="index.html"/> 

  
  <script src="../../_static/js/modernizr.min.js"></script>

</head>

<body class="wy-body-for-nav" role="document">

   
  <div class="wy-grid-for-nav">

    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search">
          

          
            <a href="../../index.html" class="icon icon-home"> cqparts
          

          
            
            <img src="../../_static/dark.svg" class="logo" />
          
          </a>

          
            
            
              <div class="version">
                0.2
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">Contents:</span></p>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../../cqparts/index.html"><code class="docutils literal"><span class="pre">cqparts</span></code> Module</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../tutorials/index.html">Tutorials</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="../index.html"><code class="docutils literal"><span class="pre">cqparts_fasteners</span></code> Module</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="../build_cycle.html"><code class="docutils literal"><span class="pre">Fastener</span></code> Build Cycle</a></li>
<li class="toctree-l2"><a class="reference internal" href="../built-in/index.html">Example: Built In</a></li>
<li class="toctree-l2 current"><a class="reference internal" href="index.html">Example: Easy Install</a><ul class="current">
<li class="toctree-l3 current"><a class="current reference internal" href="#">Component Parts</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#wood-screw">Wood Screw</a></li>
<li class="toctree-l4"><a class="reference internal" href="#anchor">Anchor</a></li>
<li class="toctree-l4"><a class="reference internal" href="#wood-panel">Wood Panel</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="exact-fastener.html">Exactly Sized Fastener</a></li>
<li class="toctree-l3"><a class="reference internal" href="catalogue-fastener.html">Catalogue Selected Fastener</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="../biscuit/index.html">Example: Biscuit Join</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../../examples/index.html">Examples</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../api/modules.html">Module APIs</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../todo.html">TODO List</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" role="navigation" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../index.html">cqparts</a>
        
      </nav>


      
      <div class="wy-nav-content">
        <div class="rst-content">
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="../../index.html">Docs</a> &raquo;</li>
        
          <li><a href="../index.html"><code class="docutils literal"><span class="pre">cqparts_fasteners</span></code> Module</a> &raquo;</li>
        
          <li><a href="index.html">Example: Easy Install</a> &raquo;</li>
        
      <li>Component Parts</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
        
      </li>
    
  </ul>

  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="component-parts">
<span id="fasteners-easy-install-parts"></span><h1>Component Parts<a class="headerlink" href="#component-parts" title="Permalink to this headline">¶</a></h1>
<p>The composition of this fastener is relatively simple; we smiply have 2 parts
grouped into a single mechanical fastener.</p>
<div class="highlight-default"><div class="highlight"><pre><span></span>easy_fastener_1
   ├─○ wood_screw
   └─○ anchor
</pre></div>
</div>
<p>And to demonstrate its function, these will be used to connect 2 wooden panels.
So we’ll need the panels too.</p>
<div class="section" id="wood-screw">
<h2>Wood Screw<a class="headerlink" href="#wood-screw" title="Permalink to this headline">¶</a></h2>
<p>Wood screw will use <a class="reference internal" href="../../api/cqparts_fasteners.html#cqparts_fasteners.male.MaleFastenerPart" title="cqparts_fasteners.male.MaleFastenerPart"><code class="xref py py-class docutils literal"><span class="pre">MaleFastenerPart</span></code></a>
as a basis.</p>
<ul class="simple">
<li><strong>screw body</strong> : built from
<a class="reference internal" href="../../api/cqparts_fasteners.html#cqparts_fasteners.male.MaleFastenerPart" title="cqparts_fasteners.male.MaleFastenerPart"><code class="xref py py-class docutils literal"><span class="pre">MaleFastenerPart</span></code></a>, then modified.</li>
<li><strong>shaft</strong> : we’ll add the bore-sized shaft (with some cylindrical cut-outs)
to the neck of the screw.</li>
</ul>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">cadquery</span>
<span class="kn">import</span> <span class="nn">cqparts</span>
<span class="kn">from</span> <span class="nn">cqparts.params</span> <span class="k">import</span> <span class="o">*</span>
<span class="kn">from</span> <span class="nn">cqparts_fasteners.params</span> <span class="k">import</span> <span class="n">HeadType</span><span class="p">,</span> <span class="n">DriveType</span><span class="p">,</span> <span class="n">ThreadType</span>
<span class="kn">from</span> <span class="nn">cqparts_fasteners.male</span> <span class="k">import</span> <span class="n">MaleFastenerPart</span>
<span class="kn">from</span> <span class="nn">cqparts.display</span> <span class="k">import</span> <span class="n">display</span><span class="p">,</span> <span class="n">render_props</span>
<span class="kn">from</span> <span class="nn">cqparts.constraint</span> <span class="k">import</span> <span class="n">Mate</span>
<span class="kn">from</span> <span class="nn">cqparts.utils</span> <span class="k">import</span> <span class="n">CoordSystem</span>


<span class="k">class</span> <span class="nc">WoodScrew</span><span class="p">(</span><span class="n">MaleFastenerPart</span><span class="p">):</span>
    <span class="c1"># --- override MaleFastenerPart parameters</span>
    <span class="c1"># sub-parts</span>
    <span class="n">head</span> <span class="o">=</span> <span class="n">HeadType</span><span class="p">(</span><span class="n">default</span><span class="o">=</span><span class="p">(</span><span class="s1">&#39;cheese&#39;</span><span class="p">,</span> <span class="p">{</span>
        <span class="s1">&#39;diameter&#39;</span><span class="p">:</span> <span class="mi">4</span><span class="p">,</span>
        <span class="s1">&#39;height&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">,</span>
    <span class="p">}),</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;screw&#39;s head&quot;</span><span class="p">)</span>
    <span class="n">drive</span> <span class="o">=</span> <span class="n">DriveType</span><span class="p">(</span><span class="n">default</span><span class="o">=</span><span class="p">(</span><span class="s1">&#39;phillips&#39;</span><span class="p">,</span> <span class="p">{</span>
        <span class="s1">&#39;diameter&#39;</span><span class="p">:</span> <span class="mf">3.5</span><span class="p">,</span>
        <span class="s1">&#39;depth&#39;</span><span class="p">:</span> <span class="mf">2.5</span><span class="p">,</span>
        <span class="s1">&#39;width&#39;</span><span class="p">:</span> <span class="mf">0.5</span><span class="p">,</span>
    <span class="p">}),</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;screw&#39;s drive&quot;</span><span class="p">)</span>
    <span class="n">thread</span> <span class="o">=</span> <span class="n">ThreadType</span><span class="p">(</span><span class="n">default</span><span class="o">=</span><span class="p">(</span><span class="s1">&#39;triangular&#39;</span><span class="p">,</span> <span class="p">{</span>
        <span class="s1">&#39;diameter&#39;</span><span class="p">:</span> <span class="mi">5</span><span class="p">,</span>  <span class="c1"># outer</span>
        <span class="s1">&#39;diameter_core&#39;</span><span class="p">:</span> <span class="mf">4.3</span><span class="p">,</span>  <span class="c1"># inner</span>
        <span class="s1">&#39;pitch&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">,</span>
        <span class="s1">&#39;angle&#39;</span><span class="p">:</span> <span class="mi">30</span><span class="p">,</span>
    <span class="p">}),</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;screw&#39;s thread&quot;</span><span class="p">)</span>

    <span class="c1"># scalars</span>
    <span class="n">neck_diam</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;neck diameter&quot;</span><span class="p">)</span>
    <span class="n">neck_length</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;length from base of head to end of neck&quot;</span><span class="p">)</span>
    <span class="n">length</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">50</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;length from base of head to end of thread&quot;</span><span class="p">)</span>

    <span class="c1"># --- parameters unique for this class</span>
    <span class="n">neck_exposed</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;length of neck exposed below head&quot;</span><span class="p">)</span>
    <span class="n">bore_diam</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">6</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;diameter of screw&#39;s bore&quot;</span><span class="p">)</span>

    <span class="n">_render</span> <span class="o">=</span> <span class="n">render_props</span><span class="p">(</span><span class="n">template</span><span class="o">=</span><span class="s1">&#39;aluminium&#39;</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">initialize_parameters</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">(</span><span class="n">WoodScrew</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="n">initialize_parameters</span><span class="p">()</span>

    <span class="k">def</span> <span class="nf">make</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="n">screw</span> <span class="o">=</span> <span class="nb">super</span><span class="p">(</span><span class="n">WoodScrew</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span><span class="o">.</span><span class="n">make</span><span class="p">()</span>

        <span class="c1"># add bore cylinder</span>
        <span class="n">bore</span> <span class="o">=</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_length</span><span class="p">))</span> \
            <span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">bore_diam</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_length</span> <span class="o">-</span> <span class="bp">self</span><span class="o">.</span><span class="n">neck_exposed</span><span class="p">)</span>
        <span class="c1"># cut out sides from bore so it takes less material</span>
        <span class="k">for</span> <span class="n">angle</span> <span class="ow">in</span> <span class="p">[</span><span class="n">i</span> <span class="o">*</span> <span class="p">(</span><span class="mi">360</span> <span class="o">/</span> <span class="mi">3</span><span class="p">)</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">3</span><span class="p">)]:</span>
            <span class="n">slice_obj</span> <span class="o">=</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span>
                <span class="s1">&#39;XY&#39;</span><span class="p">,</span>
                <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">bore_diam</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_exposed</span> <span class="o">+</span> <span class="mi">2</span><span class="p">))</span>
            <span class="p">)</span><span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">bore_diam</span> <span class="o">/</span> <span class="mi">3</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="o">-</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_length</span> <span class="o">-</span> <span class="bp">self</span><span class="o">.</span><span class="n">neck_exposed</span> <span class="o">-</span> <span class="mi">4</span><span class="p">))</span> \
                <span class="o">.</span><span class="n">rotate</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">1</span><span class="p">),</span> <span class="n">angle</span><span class="p">)</span>
            <span class="n">bore</span> <span class="o">=</span> <span class="n">bore</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">slice_obj</span><span class="p">)</span>
        <span class="n">screw</span> <span class="o">=</span> <span class="n">screw</span><span class="o">.</span><span class="n">union</span><span class="p">(</span><span class="n">bore</span><span class="p">)</span>

        <span class="k">return</span> <span class="n">screw</span>

    <span class="k">def</span> <span class="nf">make_cutter</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># we won&#39;t use MaleFastenerPart.make_cutter() because it</span>
        <span class="c1"># implements an access hole that we don&#39;t need.</span>
        <span class="n">cutter</span> <span class="o">=</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">head</span><span class="o">.</span><span class="n">height</span><span class="p">))</span> \
            <span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">bore_diam</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="o">-</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_length</span> <span class="o">+</span> <span class="bp">self</span><span class="o">.</span><span class="n">head</span><span class="o">.</span><span class="n">height</span><span class="p">))</span>
        <span class="n">cutter</span> <span class="o">=</span> <span class="n">cutter</span><span class="o">.</span><span class="n">union</span><span class="p">(</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">thread</span><span class="o">.</span><span class="n">make_pilothole_cutter</span><span class="p">()</span><span class="o">.</span><span class="n">translate</span><span class="p">((</span>
                <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">length</span>
            <span class="p">))</span>
        <span class="p">)</span>
        <span class="k">return</span> <span class="n">cutter</span>

    <span class="k">def</span> <span class="nf">make_simple</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># in this case, the cutter solid serves as a good simplified</span>
        <span class="c1"># model of the screw.</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">make_cutter</span><span class="p">()</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">mate_threadstart</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span><span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_length</span><span class="p">)))</span>
</pre></div>
</div>
<p>So to illustrate what we’ve just made:</p>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="n">screw</span> <span class="o">=</span> <span class="n">Screw</span><span class="p">()</span>
<span class="n">display</span><span class="p">(</span><span class="n">screw</span><span class="p">)</span>
</pre></div>
</div>
<iframe class="model-display"
    src="../../_static/iframes/easy-install/screw.html"
    height="300px" width="100%"
></iframe></div>
<div class="section" id="anchor">
<h2>Anchor<a class="headerlink" href="#anchor" title="Permalink to this headline">¶</a></h2>
<p>The anchor is composed of:</p>
<ul class="simple">
<li><strong>main body</strong> : the anchor will be cut from a large cylindrical block.</li>
<li><strong>neck slot</strong> : slot alowing woodscrew’s neck access.</li>
<li><strong>head slot</strong> : conical wedge to pull on screwhead when installed.</li>
<li><strong>access port</strong> : 1 quadrant cut out to to alow screwhead access.</li>
<li><strong>screw drive</strong> : to allow user to apply a screwdriver to install.</li>
</ul>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">math</span> <span class="k">import</span> <span class="n">sin</span><span class="p">,</span> <span class="n">cos</span><span class="p">,</span> <span class="n">pi</span>

<span class="k">class</span> <span class="nc">Anchor</span><span class="p">(</span><span class="n">cqparts</span><span class="o">.</span><span class="n">Part</span><span class="p">):</span>
    <span class="c1"># sub-parts</span>
    <span class="n">drive</span> <span class="o">=</span> <span class="n">DriveType</span><span class="p">(</span><span class="n">default</span><span class="o">=</span><span class="p">(</span><span class="s1">&#39;cross&#39;</span><span class="p">,</span> <span class="p">{</span>
        <span class="s1">&#39;diameter&#39;</span><span class="p">:</span> <span class="mi">5</span><span class="p">,</span>
        <span class="s1">&#39;width&#39;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span>
        <span class="s1">&#39;depth&#39;</span><span class="p">:</span> <span class="mf">2.5</span><span class="p">,</span>
    <span class="p">}),</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;anchor&#39;s drive&quot;</span><span class="p">)</span>

    <span class="c1"># scalars</span>
    <span class="n">diameter</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;diameter of anchor&quot;</span><span class="p">)</span>
    <span class="n">height</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;height of anchor&quot;</span><span class="p">)</span>
    <span class="n">neck_diameter</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;width of screw neck&quot;</span><span class="p">)</span>
    <span class="n">head_diameter</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">4</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;width of screw head&quot;</span><span class="p">)</span>
    <span class="n">spline_point_count</span> <span class="o">=</span> <span class="n">IntRange</span><span class="p">(</span><span class="mi">4</span><span class="p">,</span> <span class="mi">200</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;number of spiral spline points&quot;</span><span class="p">)</span>
    <span class="n">ratio_start</span> <span class="o">=</span> <span class="n">FloatRange</span><span class="p">(</span><span class="mf">0.5</span><span class="p">,</span> <span class="mf">0.99</span><span class="p">,</span> <span class="mf">0.99</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;radius ratio of wedge start&quot;</span><span class="p">)</span>
    <span class="n">ratio_end</span> <span class="o">=</span> <span class="n">FloatRange</span><span class="p">(</span><span class="mf">0.01</span><span class="p">,</span> <span class="mf">0.8</span><span class="p">,</span> <span class="mf">0.7</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;radius ratio of wedge end&quot;</span><span class="p">)</span>

    <span class="n">_render</span> <span class="o">=</span> <span class="n">render_props</span><span class="p">(</span><span class="n">color</span><span class="o">=</span><span class="p">(</span><span class="mi">100</span><span class="p">,</span> <span class="mi">100</span><span class="p">,</span> <span class="mi">150</span><span class="p">))</span>  <span class="c1"># dark blue</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">wedge_radii</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="p">(</span>
            <span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> <span class="o">*</span> <span class="bp">self</span><span class="o">.</span><span class="n">ratio_start</span><span class="p">,</span>  <span class="c1"># start radius</span>
            <span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> <span class="o">*</span> <span class="bp">self</span><span class="o">.</span><span class="n">ratio_end</span>  <span class="c1"># end radius</span>
        <span class="p">)</span>

    <span class="k">def</span> <span class="nf">make</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="n">obj</span> <span class="o">=</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)</span>

        <span class="c1"># neck slot : eliminate screw neck interference</span>
        <span class="n">obj</span> <span class="o">=</span> <span class="n">obj</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span>
            <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="p">((</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_diameter</span> <span class="o">+</span> <span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)))</span> \
                <span class="o">.</span><span class="n">moveTo</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">lineTo</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">threePointArc</span><span class="p">(</span>
                    <span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">),</span>
                    <span class="p">(</span><span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span>
                <span class="p">)</span> \
                <span class="o">.</span><span class="n">close</span><span class="p">()</span> \
                <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">neck_diameter</span><span class="p">)</span>
        <span class="p">)</span>

        <span class="c1"># head slot : form a circular wedge with remaining material</span>
        <span class="p">(</span><span class="n">start_r</span><span class="p">,</span> <span class="n">end_r</span><span class="p">)</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">wedge_radii</span>
        <span class="n">angles_radius</span> <span class="o">=</span> <span class="p">(</span>  <span class="c1"># as generator</span>
            <span class="p">(</span>
                <span class="p">(</span><span class="n">i</span> <span class="o">*</span> <span class="p">(</span><span class="n">pi</span> <span class="o">/</span> <span class="bp">self</span><span class="o">.</span><span class="n">spline_point_count</span><span class="p">)),</span>  <span class="c1"># angle</span>
                <span class="n">start_r</span> <span class="o">+</span> <span class="p">((</span><span class="n">end_r</span> <span class="o">-</span> <span class="n">start_r</span><span class="p">)</span> <span class="o">*</span> <span class="p">(</span><span class="n">i</span> <span class="o">/</span> <span class="nb">float</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">spline_point_count</span><span class="p">)))</span>  <span class="c1"># radius</span>
            <span class="p">)</span>
            <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">spline_point_count</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>  <span class="c1"># avoid zero angle</span>
        <span class="p">)</span>
        <span class="n">points</span> <span class="o">=</span> <span class="p">[(</span><span class="n">cos</span><span class="p">(</span><span class="n">a</span><span class="p">)</span> <span class="o">*</span> <span class="n">r</span><span class="p">,</span> <span class="o">-</span><span class="n">sin</span><span class="p">(</span><span class="n">a</span><span class="p">)</span> <span class="o">*</span> <span class="n">r</span><span class="p">)</span> <span class="k">for</span> <span class="p">(</span><span class="n">a</span><span class="p">,</span> <span class="n">r</span><span class="p">)</span> <span class="ow">in</span> <span class="n">angles_radius</span><span class="p">]</span>
        <span class="n">obj</span> <span class="o">=</span> <span class="n">obj</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span>
            <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="p">((</span><span class="bp">self</span><span class="o">.</span><span class="n">head_diameter</span> <span class="o">+</span> <span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)))</span> \
                <span class="o">.</span><span class="n">moveTo</span><span class="p">(</span><span class="n">start_r</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">spline</span><span class="p">(</span><span class="n">points</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">close</span><span class="p">()</span> \
                <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">head_diameter</span><span class="p">)</span>
        <span class="p">)</span>

        <span class="c1"># access port : remove a quadrant to alow screw&#39;s head through</span>
        <span class="n">obj</span> <span class="o">=</span> <span class="n">obj</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span>
            <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span> <span class="o">-</span> <span class="bp">self</span><span class="o">.</span><span class="n">head_diameter</span><span class="p">)</span> <span class="o">/</span> <span class="mi">2</span><span class="p">))</span> \
                <span class="o">.</span><span class="n">rect</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="n">centered</span><span class="o">=</span><span class="kc">False</span><span class="p">)</span> \
                <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)</span>
        <span class="p">)</span>

        <span class="c1"># screw drive : to apply torque to anchor for installation</span>
        <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">drive</span><span class="p">:</span>
            <span class="n">obj</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">drive</span><span class="o">.</span><span class="n">apply</span><span class="p">(</span><span class="n">obj</span><span class="p">)</span>  <span class="c1"># top face is on origin XY plane</span>

        <span class="k">return</span> <span class="n">obj</span>

    <span class="k">def</span> <span class="nf">make_simple</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># Just return the core cylinder</span>
        <span class="k">return</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">make_cutter</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># A solid to cut away from another; makes room to install the anchor</span>
        <span class="k">return</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">,</span> <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">))</span> \
            <span class="o">.</span><span class="n">circle</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">extrude</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span> <span class="o">+</span> <span class="mi">1000</span><span class="p">)</span>  <span class="c1"># 1m bore depth</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">mate_screwhead</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># The location of the screwhead in it&#39;s theoretical tightened mid-point</span>
        <span class="c1">#   (well, not really, but this is just a demo)</span>
        <span class="p">(</span><span class="n">start_r</span><span class="p">,</span> <span class="n">end_r</span><span class="p">)</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">wedge_radii</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span>
            <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="p">((</span><span class="n">start_r</span> <span class="o">+</span> <span class="n">end_r</span><span class="p">)</span> <span class="o">/</span> <span class="mi">2</span><span class="p">),</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span> <span class="o">/</span> <span class="mi">2</span><span class="p">),</span>
            <span class="n">xDir</span><span class="o">=</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span>
            <span class="n">normal</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
        <span class="p">))</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">mate_center</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># center of object, along screw&#39;s rotation axis</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span><span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)))</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">mate_base</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># base of object (for 3d printing placement, maybe)</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span><span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="bp">self</span><span class="o">.</span><span class="n">height</span><span class="p">)))</span>
</pre></div>
</div>
<p>What we’ve made isn’t perfect, but it will do for this tutorial.
Besides, that’s more than enough code:</p>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="n">anchor</span> <span class="o">=</span> <span class="n">Anchor</span><span class="p">()</span>
<span class="n">display</span><span class="p">(</span><span class="n">anchor</span><span class="p">)</span>
</pre></div>
</div>
<iframe class="model-display"
    src="../../_static/iframes/easy-install/anchor.html"
    height="300px" width="100%"
></iframe></div>
<div class="section" id="wood-panel">
<h2>Wood Panel<a class="headerlink" href="#wood-panel" title="Permalink to this headline">¶</a></h2>
<p>We’ll also need to create some wooden panels that we intend to join using
the <em>fastener</em>.</p>
<p>It’s essentially just a <em>box</em> shape, but we’ll add some <em>mate</em> points to alow
easy alignment.</p>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">WoodPanel</span><span class="p">(</span><span class="n">cqparts</span><span class="o">.</span><span class="n">Part</span><span class="p">):</span>
    <span class="n">thickness</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">15</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;thickness of panel&quot;</span><span class="p">)</span>
    <span class="n">width</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">100</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;panel width&quot;</span><span class="p">)</span>
    <span class="n">length</span> <span class="o">=</span> <span class="n">PositiveFloat</span><span class="p">(</span><span class="mi">100</span><span class="p">,</span> <span class="n">doc</span><span class="o">=</span><span class="s2">&quot;panel length&quot;</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">make</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="n">cadquery</span><span class="o">.</span><span class="n">Workplane</span><span class="p">(</span><span class="s1">&#39;XY&#39;</span><span class="p">)</span> \
            <span class="o">.</span><span class="n">box</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">length</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">width</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">thickness</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">mate_end</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="c1"># center of +x face</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span>
            <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">length</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span>
            <span class="n">xDir</span><span class="o">=</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="mi">1</span><span class="p">),</span>
            <span class="n">normal</span><span class="o">=</span><span class="p">(</span><span class="o">-</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span>
        <span class="p">))</span>

    <span class="k">def</span> <span class="nf">get_mate_edge</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">thickness</span><span class="p">):</span>
        <span class="k">return</span> <span class="n">Mate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">CoordSystem</span><span class="p">(</span>
            <span class="n">origin</span><span class="o">=</span><span class="p">((</span><span class="bp">self</span><span class="o">.</span><span class="n">length</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span> <span class="o">-</span> <span class="p">(</span><span class="n">thickness</span> <span class="o">/</span> <span class="mi">2</span><span class="p">),</span> <span class="mi">0</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">thickness</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
        <span class="p">))</span>
</pre></div>
</div>
<div class="highlight-default"><div class="highlight"><pre><span></span><span class="n">panel</span> <span class="o">=</span> <span class="n">WoodPanel</span><span class="p">()</span>
<span class="n">display</span><span class="p">(</span><span class="n">panel</span><span class="p">)</span>
</pre></div>
</div>
<iframe class="model-display"
    src="../../_static/iframes/easy-install/panel.html"
    height="300px" width="100%"
></iframe><p>Now that we have all the parts we need, the next section will work on combining
these into an <em>assembly</em>.</p>
</div>
</div>


           </div>
           <div class="articleComments">
            
           </div>
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="exact-fastener.html" class="btn btn-neutral float-right" title="Exactly Sized Fastener" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="index.html" class="btn btn-neutral" title="Example: Easy Install" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright 2018 Peter Boin.

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/snide/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  

    <script type="text/javascript">
        var DOCUMENTATION_OPTIONS = {
            URL_ROOT:'../../',
            VERSION:'0.2.1',
            COLLAPSE_INDEX:false,
            FILE_SUFFIX:'.html',
            HAS_SOURCE:  true,
            SOURCELINK_SUFFIX: '.txt'
        };
    </script>
      <script type="text/javascript" src="../../_static/jquery.js"></script>
      <script type="text/javascript" src="../../_static/underscore.js"></script>
      <script type="text/javascript" src="../../_static/doctools.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

  

  
  
    <script type="text/javascript" src="../../_static/js/theme.js"></script>
  

  
  
  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.StickyNav.enable();
      });
  </script>
   

</body>
</html>